if(EXISTS "/data/data/com.termux/files/home/IVANNA-OMEGA-SUPREME/app/src/main/cpp/tests/build-tests/gammatone_numerical_stability[1]_tests.cmake")
  include("/data/data/com.termux/files/home/IVANNA-OMEGA-SUPREME/app/src/main/cpp/tests/build-tests/gammatone_numerical_stability[1]_tests.cmake")
else()
  add_test(gammatone_numerical_stability_NOT_BUILT gammatone_numerical_stability_NOT_BUILT)
endif()
